path: C:\Users\squddus\Documents\GitHub\2025-YOLO-Vehicle-Tracking\UA-DETRAC-DATASET-10K.v2-2024-11-14-3-48pm.yolov11

train: train\images
val: valid\images
test: test\images

nc: 4
names: ['bus', 'car', 'truck', 'van']

roboflow:
  workspace: rjacaac1
  project: ua-detrac-dataset-10k
  version: 2
  license: Private
  url: https://universe.roboflow.com/rjacaac1/ua-detrac-dataset-10k/dataset/2
